version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: projeto-base-clean-arch-modular
    restart: unless-stopped
