CREATE TABLE USUARIO (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    login VARCHAR(100) NOT NULL,
    passaword VARCHAR(100) NOT NULL,
    role VARCHAR(100) NOT NULL
);

INSERT INTO USUARIO (login, passaword, role) VALUES ('admin', '$2a$10$365wRWMmVganHHHmU0KRT.LD2WvtHW24dcLjkpPITX3qQXjhCY14.', 'ADMIN');